Import-module OperationsManager
#Modifcar Tiempo en minutos AddMinutes(10), Modifcar Tiempo en Horas AddHours(10),Modifcar Tiempo en dias AddDays(1)
$Time=((Get-date).AddMinute(6))

#Recuperamos los Grupos y lo guardamos en una variable
$FimraWatcher = Get-SCOMClassInstance "@FIRMA watcher computers group"
$AduanasComunica = Get-SCOMClassInstance "Aplicacion Aduanas Comunica"
$AduanetXML = Get-SCOMClassInstance "Aplicacion AduanetXML"
$Cites = Get-SCOMClassInstance "Aplicacion Cites"
$Estacice = Get-SCOMClassInstance "Aplicacion Estacice"
$Indus = Get-SCOMClassInstance "Aplicacion Indus"
$Licencias = Get-SCOMClassInstance "Aplicacion Licencias"
$Portales = Get-SCOMClassInstance "Aplicacion Portales"
$RAE = Get-SCOMClassInstance "Aplicacion RAE"
$Sigede = Get-SCOMClassInstance "Aplicacion Sigede"
$DomainController = Get-SCOMClassInstance "AD Domain Controller Group (Windows Server 2008 and above)"
$AlarmasRAE = Get-SCOMClassInstance "Alarmas RAE"
$AlarmasSigede = Get-SCOMClassInstance "Alarmas Sigede"
$AllArrays = Get-SCOMClassInstance "All Arrays"
$AllOpMgrsObj = Get-SCOMClassInstance "All Operations Manager Object Group"
$AllComputers = Get-SCOMClassInstance "All Windows Computers"
$ClusterRoles = Get-SCOMClassInstance "Cluster Roles"
$DHCPServers = Get-SCOMClassInstance "DHCP Servers"
$DHCPScopes = Get-SCOMClassInstance "DHCP Scopes"
$DNSServers = Get-SCOMClassInstance "DNS 2012 R2 Servers"
$IISInstance = Get-SCOMClassInstance "IIS Instance Group"
$Exchange2010All = Get-SCOMClassInstance "Microsoft Exchange 2010 All Entities Group"
$NLBClusters = Get-SCOMClassInstance "NLB Clusters Group"
$PKICertificates = Get-SCOMClassInstance "PKI Certificates and CRLs Group"
$ServerRoles = Get-SCOMClassInstance "Server Roles Group"
$SharePoint2010 = Get-SCOMClassInstance "SharePoint Foundation 2010 Objects Group"
$SharePoint = Get-SCOMClassInstance "SharePoint Foundation Objects Group"
$SQLComponents = Get-SCOMClassInstance "SQL Components"
$SQLInstances = Get-SCOMClassInstance "SQL Instances"
$SQLAgents = Get-SCOMClassInstance "SQL Server Agents"

#Ponemos en modo mantenimiento los grupos durante el tiempo indicado en $Time y añadimos comentario
Start-SCOMMaintenanceMode -Instance $FimraWatcher -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $AduanasComunica -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $AduanetXML -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $Cites -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $Estacice -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $Indus -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $Licencias -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $Portales -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $RAE -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $Sigede -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $DomainController -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $AlarmasRAE -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $AlarmasSigede -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $AllArrays -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $AllOpMgrsObj -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $AllComputers -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $ClusterRoles -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $DHCPServers -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $DHCPScopes -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $DNSServers -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $IISInstance -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $Exchange2010All -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $NLBClusters -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $PKICertificates -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $ServerRoles -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $SharePoint2010 -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $SharePoint -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $SQLComponents -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $SQLInstances -EndTime $Time -Comment "Parada Planeada Comunicaciones"
Start-SCOMMaintenanceMode -Instance $SQLAgents -EndTime $Time -Comment "Parada Planeada Comunicaciones"